# Generated by Django 4.0 on 2022-04-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades de Pacientes',
            },
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'verbose_name': 'Mis Pacientes', 'verbose_name_plural': 'Lista de Pacientes'},
        ),
    ]
