# Generated by Django 4.0 on 2022-04-23 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_pacientess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pacientess',
        ),
    ]
